### ISSUE TITLE
Meteor GraphQL Kitchensink

### ISSUE THREAD

**Issue by mstn** [mstn/graphql#13]
A complex demo of meteor+graphql with real world features
- [ ] pagination/infinite scrolling
  - [ ] smart scrolling, remember last position
- [ ] advanced search on a list of items
- [ ] counters grouped by categories
- [ ] perm links

**Comment by mstn** [comment]
not interested anymore for now
