### ISSUE TITLE
Formal abstract semantics for GraphQL

### ISSUE THREAD

**Issue by mstn** [mstn/graphql#7]
List of GraphQL features
- [x] Queries ~#4~ #12 
- [x] Type system ~#4~ #12 
- [x] Execution semantics ~#4~ #12 
- [x] Inline Fragments #12
- [x] Unions #12
- [ ] Fragments 
- [ ] Alias
- [ ] Enums
- [ ] Directives
- [ ] Introspection
- [ ] Interfaces
- [x] Error Handling
- [ ] Non Null types

Our assumptions/simplifications
- [x] root type can be any type #12 
- [x] ~Named queries with parameters~ -> arguments are free vars in query #12 
- [x] ~mutation~ -> mutation = query with side effects, for now, we do not have any special syntax to distinguish them #12 
- [x] no special type for input objects #12 

Desirable properties (or what can we say about the abstract lang?)
- [ ] safety 
  - [ ] progress
  - [ ] preservation
- [ ] uniqueness of typing
