### ISSUE TITLE
Extending GraphQL

### ISSUE THREAD

**Issue by mstn** [mstn/graphql#8]
Some ideas to extend GraphQL.
- [ ] Recursion. As far I know, it is forbidden in current spec because it could yield infinite results. However, it is useful. A recursive query represents a potentially infinite result, but we do not have to send infinite data to the client. Some examples:
  - [ ] pagination (e.g. infinite scrolling)
  - [ ] cyclic data structures (e.g. I am a friend of my friends). Currently, data are unfolded and cyclic relations are potentially infinite, but folded data have a finite representation as graphs!
- [ ] Restructuring. Alias are a simple mechanism to rename query properties. It could have sense also to explore more complex post-processing.
